export const API_ERROR = 'API_ERROR';
export const SHOW_DATA = 'SHOW_DATA';
export const UPDATE_DATA = 'UPDATE_DATA';
export const REGISTER_FRESHER_DATA = 'REGISTER_FRESHER_DATA';
export const UPDATE_REGISTER_FRESHER_DATA = 'UPDATE_REGISTER_FRESHER_DATA';
export const CLEAR_REGISTER_FRESHER_DATA = 'CLEAR_REGISTER_FRESHER_DATA';
