export const API_ERROR = 'API_ERROR';
export const REGISTER_DATA = 'REGISTER_DATA';
export const UPDATE_REGISTER_DATA = 'UPDATE_REGISTER_DATA';
export const CLEAR_REGISTER_DATA = 'CLEAR_REGISTER_DATA';
export const RESUME_CONTACT_DATA = 'RESUME_CONTACT_DATA';
export const UPDATE_RESUME_CONTACT_DATA = 'UPDATE_RESUME_CONTACT_DATA';
export const CLEAR_RESUME_CONTACT_DATA = 'CLEAR_RESUME_CONTACT_DATA';
