export const API_ERROR = 'API_ERROR';
export const GET_TOKEN = 'GET_TOKEN';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const GET_ALL_JOBS = 'GET_ALL_JOBS';
export const UPDATE_ALL_JOBS = 'UPDATE_ALL_JOBS';
export const GET_JOB_POSITION_BY_ID = 'GET_JOB_POSITION_BY_ID';
export const UPDATE_JOB_POSITION_BY_ID = 'UPDATE_JOB_POSITION_BY_ID';
export const CLEAR_JOB_POSITION_BY_ID = 'CLEAR_JOB_POSITION_BY_ID';
