/* eslint-disable linebreak-style */
export const coachData = [
  {
    id: '1',
    calls: '300',
    imageUrl: 'images/founders/jeet.jpg',
    coachName: 'Jeet Jha',
    designation: 'Global delvery head at Hebbale Academy',
    subject: ['JavaScript,', 'ReactJS, ', 'Python '],
    language: ['Hindi, ', 'English'],
    experience: '10',
    price: '18',
  },
  {
    id: '2',
    calls: '400',
    imageUrl: '',
    coachName: 'Supriya',
    designation: 'Senior Developer at Barclays',
    subject: ['JavaScript, ', 'ReactJS, ', 'Python'],
    language: ['Hindi, ', 'English'],
    experience: '20',
    price: '20',
  },
  {
    id: '3',
    calls: '600',
    imageUrl: '',
    coachName: 'Nikitha',
    designation: 'Senior Developer',
    subject: ['JavaScript, ', 'ReactJS, ', 'Python'],
    language: ['Hindi, ', 'English'],
    experience: '15',
    price: '30',
  },
  {
    id: '3',
    calls: '600',
    imageUrl: '',
    coachName: 'Vivek',
    designation: 'React js Developer',
    subject: ['JavaScript, ', 'ReactJS, ', 'Python'],
    language: ['Hindi, ', 'English'],
    experience: '15',
    price: '30',
  },
  {
    id: '3',
    calls: '600',
    imageUrl: '',
    coachName: 'sharon',
    designation: 'Senior Developer',
    subject: ['JavaScript, ', 'ReactJS, ', 'Python'],
    language: ['Hindi, ', 'English'],
    experience: '15',
    price: '30',
  },
  {
    id: '3',
    calls: '600',
    imageUrl: '',
    coachName: 'Khalid',
    designation: 'Developer',
    subject: ['JavaScript, ', 'ReactJS, ', 'Python'],
    language: ['Hindi, ', 'English'],
    experience: '15',
    price: '30',
  },
  {
    id: '3',
    calls: '600',
    imageUrl: '',
    coachName: 'Chaitrika',
    designation: 'Junior Developer',
    subject: ['JavaScript, ', 'ReactJS, ', 'Python'],
    language: ['Hindi, ', 'English'],
    experience: '15',
    price: '30',
  },
  {
    id: '3',
    calls: '600',
    imageUrl: '',
    coachName: 'Pujitha',
    designation: 'Javascript Developer',
    subject: ['JavaScript, ', 'ReactJS, ', 'Python'],
    language: ['Hindi, ', 'English'],
    experience: '15',
    price: '30',
  },
  {
    id: '3',
    calls: '600',
    imageUrl: '',
    coachName: 'Sathwika',
    designation: 'Python Developer',
    subject: ['JavaScript, ', 'ReactJS, ', 'Python'],
    language: ['Hindi, ', 'English'],
    experience: '15',
    price: '30',
  },

];
